import { useEffect, useState } from "react";
import { useRouter } from "next/router";
import { addDoc, collection, getDocs, serverTimestamp } from "firebase/firestore";
import { db } from "../../lib/firebase";
import ProtectedRoute from "../../components/ProtectedRoute";
import Layout from "../../components/Layout";

const statuses = ["صالح", "عاطل", "تالف"];
const types = ["معدة", "سيارة", "ماكينة", "أداة", "أخرى"];

export default function AddAsset(){
 const router=useRouter(); const [workers,setWorkers]=useState([]); const [farms,setFarms]=useState([]); const [image,setImage]=useState(null); const [loading,setLoading]=useState(false);
 const [form,setForm]=useState({name:"",code:"",type:"معدة",status:"صالح",farmId:"",workerIds:[],notes:""});
 useEffect(()=>{getDocs(collection(db,"workers")).then(s=>setWorkers(s.docs.map(d=>({id:d.id,...d.data()})))); getDocs(collection(db,"farms")).then(s=>setFarms(s.docs.map(d=>({id:d.id,...d.data()}))));},[]);
 const toggleWorker=(id)=>setForm(p=>({ ...p, workerIds:p.workerIds.includes(id)?p.workerIds.filter(x=>x!==id):[...p.workerIds,id] }));
 const upload=async()=>{if(!image)return ""; const cloudName=process.env.NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME; const preset=process.env.NEXT_PUBLIC_CLOUDINARY_UPLOAD_PRESET; const data=new FormData(); data.append("file",image); data.append("upload_preset",preset); const res=await fetch(`https://api.cloudinary.com/v1_1/${cloudName}/image/upload`,{method:"POST",body:data}); const json=await res.json(); if(!json.secure_url) throw new Error("Upload failed"); return json.secure_url;};
 const submit=async(e)=>{e.preventDefault(); if(!form.name||!form.farmId) return alert("اسم المعدة والمزرعة مطلوبان"); setLoading(true); try{const farm=farms.find(f=>f.id===form.farmId); const selectedWorkers=workers.filter(w=>form.workerIds.includes(w.id)); const imageUrl=await upload(); await addDoc(collection(db,"assets"),{name:form.name,code:form.code,type:form.type,status:form.status,farmId:form.farmId,farmName:farm?.name||"",workerIds:form.workerIds,workers:selectedWorkers.map(w=>({id:w.id,name:w.name,phone:w.phone||""})),workerNames:selectedWorkers.map(w=>w.name).join("، "),imageUrl,notes:form.notes,createdAt:serverTimestamp(),updatedAt:serverTimestamp()}); router.push("/assets");}catch(e){console.error(e); alert("حدث خطأ أثناء الحفظ"); setLoading(false);}};
 return <ProtectedRoute><Layout title="إضافة معدة"><form onSubmit={submit} className="page-card max-w-4xl p-5 space-y-4"><div className="grid gap-4 md:grid-cols-2"><input className="form-input" placeholder="اسم المعدة" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input className="form-input" placeholder="كود أو رقم المعدة اختياري" value={form.code} onChange={e=>setForm({...form,code:e.target.value})}/></div><div className="grid gap-4 md:grid-cols-3"><select className="form-input" value={form.farmId} onChange={e=>setForm({...form,farmId:e.target.value})}><option value="">اختر المزرعة</option>{farms.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select><select className="form-input" value={form.type} onChange={e=>setForm({...form,type:e.target.value})}>{types.map(x=><option key={x}>{x}</option>)}</select><select className="form-input" value={form.status} onChange={e=>setForm({...form,status:e.target.value})}>{statuses.map(x=><option key={x}>{x}</option>)}</select></div><div><label className="mb-2 block text-sm font-black text-slate-700">العمال المستلمون للمعدة</label><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{workers.map(w=><label key={w.id} className={`flex cursor-pointer items-center gap-3 rounded-2xl border p-3 text-sm font-bold ${form.workerIds.includes(w.id)?"border-green-600 bg-green-50 text-green-800":"border-slate-200 bg-white text-slate-700"}`}><input type="checkbox" checked={form.workerIds.includes(w.id)} onChange={()=>toggleWorker(w.id)}/>{w.name}</label>)}</div></div><input type="file" accept="image/*" capture="environment" className="form-input" onChange={e=>setImage(e.target.files?.[0]||null)}/><textarea className="form-input h-28" placeholder="ملاحظات" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/><button disabled={loading} className="btn-primary">{loading?"جاري الحفظ والرفع...":"حفظ المعدة"}</button></form></Layout></ProtectedRoute>;
}
