import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/router";
import Link from "next/link";
import { collection, deleteDoc, doc, getDocs, orderBy, query } from "firebase/firestore";
import { db } from "../../lib/firebase";
import ProtectedRoute from "../../components/ProtectedRoute";
import Layout from "../../components/Layout";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faPlus, faPen, faTrash, faMagnifyingGlass } from "@fortawesome/free-solid-svg-icons";

const badgeClass=(s)=>s==="صالح"?"bg-green-50 text-green-700":s==="عاطل"?"bg-amber-50 text-amber-700":"bg-red-50 text-red-700";
export default function Assets(){
 const router=useRouter(); const [items,setItems]=useState([]); const [status,setStatus]=useState(""); const [search,setSearch]=useState(""); const [preview,setPreview]=useState(null);
 const load=async()=>{const s=await getDocs(query(collection(db,"assets"),orderBy("createdAt","desc"))); setItems(s.docs.map(d=>({id:d.id,...d.data()})));}; useEffect(()=>{load();},[]); useEffect(()=>{ if(router.query.status) setStatus(String(router.query.status)); },[router.query.status]);
 const remove=async(id)=>{if(confirm("هل تريد حذف المعدة؟")){await deleteDoc(doc(db,"assets",id)); load();}};
 const filtered=useMemo(()=>items.filter(a=>(!status||a.status===status)&&(!search||`${a.name} ${a.placeName||a.farmName||a.kubraName} ${a.workerNames} ${a.code}`.includes(search))),[items,status,search]);
 return <ProtectedRoute><Layout title="إدارة المعدات والعهد"><div className="mb-4 flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><div className="flex flex-wrap gap-2"><button onClick={()=>setStatus("")} className={`btn-secondary ${!status?"!bg-slate-900 !text-white":""}`}>الكل {items.length}</button>{["صالح","عاطل","تالف"].map(s=><button key={s} onClick={()=>setStatus(s)} className={`btn-secondary ${status===s?"!bg-slate-900 !text-white":""}`}>{s} {items.filter(a=>a.status===s).length}</button>)}</div><Link href="/assets/add" className="btn-primary"><FontAwesomeIcon icon={faPlus}/> إضافة معدة</Link></div><div className="page-card mb-4 p-3"><div className="flex items-center gap-2"><FontAwesomeIcon icon={faMagnifyingGlass} className="text-slate-400"/><input className="w-full bg-transparent p-2 outline-none" placeholder="بحث باسم المعدة أو المزرعة أو العامل" value={search} onChange={e=>setSearch(e.target.value)}/></div></div><div className="page-card overflow-x-auto"><table className="w-full"><thead className="bg-slate-50"><tr><th className="table-th">الصورة</th><th className="table-th">المعدة</th><th className="table-th">المكان</th><th className="table-th">العمال</th><th className="table-th">الحالة</th><th className="table-th">إجراءات</th></tr></thead><tbody>{filtered.map(a=><tr className="border-t border-slate-100" key={a.id}><td className="table-td">{a.imageUrl?<button onClick={()=>setPreview(a)}><img src={a.imageUrl} alt={a.name} className="h-16 w-24 rounded-2xl object-cover ring-1 ring-slate-200"/></button>:"-"}</td><td className="table-td"><b>{a.name}</b><p className="text-xs text-slate-400">{a.code||""}</p></td><td className="table-td"><b>{a.placeName||a.farmName||a.kubraName||"-"}</b><p className="text-xs text-slate-400">{a.placeType==="kubra"?"الكِبرة":"مزرعة"}</p></td><td className="table-td max-w-xs overflow-hidden text-ellipsis">{a.workerNames||"-"}</td><td className="table-td"><span className={`badge ${badgeClass(a.status)}`}>{a.status}</span></td><td className="table-td"><div className="flex gap-2"><Link href={`/assets/edit/${a.id}`} className="btn-secondary !p-2"><FontAwesomeIcon icon={faPen}/></Link><button onClick={()=>remove(a.id)} className="btn-danger !p-2"><FontAwesomeIcon icon={faTrash}/></button></div></td></tr>)}</tbody></table></div>{preview&&<div onClick={()=>setPreview(null)} className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 p-4"><div onClick={e=>e.stopPropagation()} className="max-h-[90vh] w-full max-w-4xl overflow-auto rounded-3xl bg-white p-4"><div className="mb-3 flex items-center justify-between"><h3 className="font-black">{preview.name}</h3><button className="btn-secondary !py-2" onClick={()=>setPreview(null)}>إغلاق</button></div><img src={preview.imageUrl} alt={preview.name} className="max-h-[75vh] w-full rounded-2xl object-contain"/></div></div>}</Layout></ProtectedRoute>;
}
