export const sprinklersSeed = [
  {
    "name": "رشاش1",
    "machine": "411",
    "towersCount": "5",
    "gear": "1/1(350)",
    "sequence": "1",
    "farmName": "الصناعيه",
    "movement": "دايري",
    "cropType": "رودس",
    "hectareNumber": "20",
    "workerName": "حسن رشاش",
    "imageUrl": ""
  },
  {
    "name": "رشاش2",
    "machine": "دينامو",
    "towersCount": "7",
    "gear": "",
    "sequence": "2",
    "farmName": "الصناعيه",
    "movement": "دايري",
    "cropType": "برسيم",
    "hectareNumber": "35",
    "workerName": "حسنين ممتاج",
    "imageUrl": ""
  },
  {
    "name": "رشاش3",
    "machine": "411",
    "towersCount": "8",
    "gear": "10/11(400)",
    "sequence": "3",
    "farmName": "الصناعيه",
    "movement": "نص",
    "cropType": "برسيم",
    "hectareNumber": "20",
    "workerName": "حسنين ممتاج",
    "imageUrl": ""
  },
  {
    "name": "رشاش5",
    "machine": "411",
    "towersCount": "7",
    "gear": "5/6(350)",
    "sequence": "5",
    "farmName": "الصناعيه",
    "movement": "نصين",
    "cropType": "برسيم",
    "hectareNumber": "38",
    "workerName": "كول محمد",
    "imageUrl": ""
  },
  {
    "name": "رشاش6",
    "machine": "411",
    "towersCount": "7",
    "gear": "1/1(350)",
    "sequence": "6",
    "farmName": "الصناعيه",
    "movement": "نصين",
    "cropType": "برسيم",
    "hectareNumber": "43",
    "workerName": "كول محمد",
    "imageUrl": ""
  },
  {
    "name": "رشاش7",
    "machine": "605",
    "towersCount": "6",
    "gear": "10/11(425)",
    "sequence": "7",
    "farmName": "الصناعيه",
    "movement": "داىري",
    "cropType": "برسيم",
    "hectareNumber": "38",
    "workerName": "بولوي",
    "imageUrl": ""
  },
  {
    "name": "رشاش8",
    "machine": "411",
    "towersCount": "5",
    "gear": "1/1(350)",
    "sequence": "8",
    "farmName": "الصناعيه",
    "movement": "دايري",
    "cropType": "برسيم",
    "hectareNumber": "25",
    "workerName": "نظر الإسلام",
    "imageUrl": ""
  },
  {
    "name": "رشاش1",
    "machine": "605",
    "towersCount": "9",
    "gear": "10/11",
    "sequence": "1",
    "farmName": "مجدل",
    "movement": "دايري",
    "cropType": "برسيم",
    "hectareNumber": "38",
    "workerName": "سلطان",
    "imageUrl": ""
  },
  {
    "name": "رشاش4",
    "machine": "411",
    "towersCount": "8",
    "gear": "1/1(350)",
    "sequence": "4",
    "farmName": "مجدل",
    "movement": "دايري",
    "cropType": "ذره",
    "hectareNumber": "31",
    "workerName": "سلمان عبد القدير",
    "imageUrl": ""
  },
  {
    "name": "رشاش6",
    "machine": "411",
    "towersCount": "8",
    "gear": "1/1(350)",
    "sequence": "6",
    "farmName": "مجدل",
    "movement": "دايري",
    "cropType": "رودس",
    "hectareNumber": "34",
    "workerName": "عبدالله صالح",
    "imageUrl": ""
  },
  {
    "name": "رشاش7",
    "machine": "411",
    "towersCount": "6",
    "gear": "1/1(350)",
    "sequence": "7",
    "farmName": "مجدل",
    "movement": "دايري",
    "cropType": "ذره",
    "hectareNumber": "26",
    "workerName": "عدي",
    "imageUrl": ""
  },
  {
    "name": "رشاش8",
    "machine": "605",
    "towersCount": "7",
    "gear": "10/11",
    "sequence": "8",
    "farmName": "مجدل",
    "movement": "دايري",
    "cropType": "رودس",
    "hectareNumber": "44",
    "workerName": "عبدالسلام",
    "imageUrl": ""
  },
  {
    "name": "رشاش9",
    "machine": "411",
    "towersCount": "6",
    "gear": "1/1(350)",
    "sequence": "9",
    "farmName": "مجدل",
    "movement": "دايري",
    "cropType": "برسيم",
    "hectareNumber": "26",
    "workerName": "عبدالسلام",
    "imageUrl": ""
  },
  {
    "name": "رشاش10",
    "machine": "411",
    "towersCount": "6",
    "gear": "1/1",
    "sequence": "10",
    "farmName": "مجدل",
    "movement": "دايري",
    "cropType": "برسيم",
    "hectareNumber": "29",
    "workerName": "امين",
    "imageUrl": ""
  },
  {
    "name": "رشاش11",
    "machine": "411",
    "towersCount": "7",
    "gear": "1/1",
    "sequence": "11",
    "farmName": "مجدل",
    "movement": "ثلاث اربع",
    "cropType": "برسيم",
    "hectareNumber": "34",
    "workerName": "امين",
    "imageUrl": ""
  },
  {
    "name": "رشاش12",
    "machine": "411",
    "towersCount": "8",
    "gear": "1/1",
    "sequence": "12",
    "farmName": "مجدل",
    "movement": "نص",
    "cropType": "رودس",
    "hectareNumber": "25",
    "workerName": "محمد اسلام",
    "imageUrl": ""
  },
  {
    "name": "رشاش13",
    "machine": "605",
    "towersCount": "7",
    "gear": "10/11",
    "sequence": "13",
    "farmName": "مجدل",
    "movement": "ثلاث اربع",
    "cropType": "برسيم",
    "hectareNumber": "32",
    "workerName": "عماد عبد الصالح عبدالله",
    "imageUrl": ""
  },
  {
    "name": "رشاش1",
    "machine": "411",
    "towersCount": "7",
    "gear": "1/1(425)",
    "sequence": "1",
    "farmName": "الخطمي",
    "movement": "دايري",
    "cropType": "برسيم",
    "hectareNumber": "40",
    "workerName": "نواب",
    "imageUrl": ""
  },
  {
    "name": "رشاش2",
    "machine": "411",
    "towersCount": "10",
    "gear": "1/1(350)",
    "sequence": "2",
    "farmName": "الخطمي",
    "movement": "دايري",
    "cropType": "رودس",
    "hectareNumber": "50",
    "workerName": "رياض",
    "imageUrl": ""
  },
  {
    "name": "رشاش3",
    "machine": "411",
    "towersCount": "7",
    "gear": "1/1(350)",
    "sequence": "3",
    "farmName": "الخطمي",
    "movement": "نصف دايري",
    "cropType": "برسيم",
    "hectareNumber": "20",
    "workerName": "فتحي محمد",
    "imageUrl": ""
  },
  {
    "name": "رشاش4",
    "machine": "411",
    "towersCount": "10",
    "gear": "1/1(350)",
    "sequence": "4",
    "farmName": "الخطمي",
    "movement": "نصف دايري",
    "cropType": "برسيم",
    "hectareNumber": "35",
    "workerName": "شمس الإسلام",
    "imageUrl": ""
  },
  {
    "name": "رشاش5",
    "machine": "411",
    "towersCount": "7",
    "gear": "1/1(350)",
    "sequence": "5",
    "farmName": "الخطمي",
    "movement": "دايري",
    "cropType": "برسيم",
    "hectareNumber": "40",
    "workerName": "فتحي محمد",
    "imageUrl": ""
  },
  {
    "name": "رشاش6",
    "machine": "411",
    "towersCount": "8",
    "gear": "1/1(350)",
    "sequence": "6",
    "farmName": "الخطمي",
    "movement": "نصف دايري",
    "cropType": "رودس",
    "hectareNumber": "25",
    "workerName": "امتياج احمد",
    "imageUrl": ""
  },
  {
    "name": "رشاش7",
    "machine": "411",
    "towersCount": "10",
    "gear": "1/1(350)",
    "sequence": "7",
    "farmName": "الخطمي",
    "movement": "دايري",
    "cropType": "رودس",
    "hectareNumber": "50",
    "workerName": "مد ولايت",
    "imageUrl": ""
  },
  {
    "name": "رشاش8",
    "machine": "411",
    "towersCount": "8",
    "gear": "1/1(350)",
    "sequence": "8",
    "farmName": "الخطمي",
    "movement": "دايري",
    "cropType": "رودس",
    "hectareNumber": "42",
    "workerName": "مد ولايت",
    "imageUrl": ""
  },
  {
    "name": "رشاش9",
    "machine": "411",
    "towersCount": "8",
    "gear": "1/1(350)",
    "sequence": "9",
    "farmName": "الخطمي",
    "movement": "دايري",
    "cropType": "رودس",
    "hectareNumber": "30",
    "workerName": "امتياج احمد",
    "imageUrl": ""
  },
  {
    "name": "رشاش10",
    "machine": "411",
    "towersCount": "8",
    "gear": "1/1(350)",
    "sequence": "10",
    "farmName": "الخطمي",
    "movement": "دايري",
    "cropType": "رودس",
    "hectareNumber": "41",
    "workerName": "صلاح الدين",
    "imageUrl": ""
  },
  {
    "name": "رشاش 11",
    "machine": "411",
    "towersCount": "8",
    "gear": "1/1(350)",
    "sequence": "11",
    "farmName": "الخطمي",
    "movement": "نصف دايري",
    "cropType": "برسيم",
    "hectareNumber": "25",
    "workerName": "صلاح الدين",
    "imageUrl": ""
  },
  {
    "name": "رشاش 1",
    "machine": "411",
    "towersCount": "8",
    "gear": "1/1",
    "sequence": "1",
    "farmName": "الحوطي",
    "movement": "نصف دايري",
    "cropType": "ذره",
    "hectareNumber": "25",
    "workerName": "ارشد وكمال",
    "imageUrl": ""
  },
  {
    "name": "رشاش2",
    "machine": "411",
    "towersCount": "8",
    "gear": "1/1",
    "sequence": "2",
    "farmName": "الحوطي",
    "movement": "نصف دايري",
    "cropType": "ذره",
    "hectareNumber": "25",
    "workerName": "ارشد وكمال",
    "imageUrl": ""
  },
  {
    "name": "رشاش3",
    "machine": "411",
    "towersCount": "9",
    "gear": "1/1",
    "sequence": "3",
    "farmName": "الحوطي",
    "movement": "نصف دايري",
    "cropType": "ذره",
    "hectareNumber": "32",
    "workerName": "كمال",
    "imageUrl": ""
  },
  {
    "name": "رشاش4",
    "machine": "411",
    "towersCount": "8",
    "gear": "",
    "sequence": "4",
    "farmName": "الحوطي",
    "movement": "نصف دايري",
    "cropType": "ذره",
    "hectareNumber": "30",
    "workerName": "ارشد وكمال",
    "imageUrl": ""
  },
  {
    "name": "رشاش5",
    "machine": "411",
    "towersCount": "9",
    "gear": "1/1",
    "sequence": "5",
    "farmName": "الحوطي",
    "movement": "نصف دايري",
    "cropType": "ذره",
    "hectareNumber": "32",
    "workerName": "ارشد وكمال",
    "imageUrl": ""
  },
  {
    "name": "رشاش6",
    "machine": "411",
    "towersCount": "8",
    "gear": "1/1",
    "sequence": "6",
    "farmName": "الحوطي",
    "movement": "نصف دايري",
    "cropType": "ذره",
    "hectareNumber": "25",
    "workerName": "ارشد وكمال",
    "imageUrl": ""
  },
  {
    "name": "رشاش9",
    "machine": "411",
    "towersCount": "7",
    "gear": "1/1",
    "sequence": "9",
    "farmName": "الحوطي",
    "movement": "نصف دايري",
    "cropType": "رودس",
    "hectareNumber": "20",
    "workerName": "ارشد وكمال",
    "imageUrl": ""
  },
  {
    "name": "رشاش10",
    "machine": "411",
    "towersCount": "5",
    "gear": "1/1",
    "sequence": "10",
    "farmName": "الحوطي",
    "movement": "دايري",
    "cropType": "رودس",
    "hectareNumber": "20",
    "workerName": "كمال",
    "imageUrl": ""
  },
  {
    "name": "رشاش11",
    "machine": "",
    "towersCount": "4",
    "gear": "",
    "sequence": "11",
    "farmName": "الحوطي",
    "movement": "",
    "cropType": "",
    "hectareNumber": "",
    "workerName": "ارشد وكمال",
    "imageUrl": ""
  },
  {
    "name": "رشاش الحوطي الجديد",
    "machine": "",
    "towersCount": "7",
    "gear": "",
    "sequence": "",
    "farmName": "الحوطي",
    "movement": "دايري",
    "cropType": "",
    "hectareNumber": "",
    "workerName": "ارشد وكمال",
    "imageUrl": ""
  },
  {
    "name": "رشاش الحوطي الجديد",
    "machine": "411",
    "towersCount": "8",
    "gear": "(350)1/1",
    "sequence": "",
    "farmName": "الحوطي",
    "movement": "",
    "cropType": "",
    "hectareNumber": "",
    "workerName": "ارشد وكمال",
    "imageUrl": ""
  },
  {
    "name": "رشاش7",
    "machine": "411",
    "towersCount": "9",
    "gear": "1/1",
    "sequence": "7",
    "farmName": "الجبلين",
    "movement": "نصف دايري",
    "cropType": "ذره",
    "hectareNumber": "32",
    "workerName": "راجو",
    "imageUrl": ""
  },
  {
    "name": "رشاش8",
    "machine": "411",
    "towersCount": "8",
    "gear": "1/1",
    "sequence": "8",
    "farmName": "الجبلين",
    "movement": "نصف دايري",
    "cropType": "ذره",
    "hectareNumber": "25",
    "workerName": "راجو",
    "imageUrl": ""
  },
  {
    "name": "رشاش12",
    "machine": "605",
    "towersCount": "9",
    "gear": ".(425)1/1",
    "sequence": "12",
    "farmName": "الجبلين",
    "movement": "ثلاث اربع دايره",
    "cropType": "برسيم",
    "hectareNumber": "35",
    "workerName": "بلال وبلال وراسل",
    "imageUrl": ""
  },
  {
    "name": "رشاش13",
    "machine": "605",
    "towersCount": "8",
    "gear": ".(425)1/1",
    "sequence": "13",
    "farmName": "الجبلين",
    "movement": "دايري",
    "cropType": "زريعه",
    "hectareNumber": "52",
    "workerName": "بلال وبلال وراسل",
    "imageUrl": ""
  },
  {
    "name": "رشاش14",
    "machine": "605",
    "towersCount": "8",
    "gear": ".(425)1/1",
    "sequence": "14",
    "farmName": "الجبلين",
    "movement": "دايري",
    "cropType": "زريعه",
    "hectareNumber": "51",
    "workerName": "بلال وبلال وراسل",
    "imageUrl": ""
  },
  {
    "name": "رشاش15",
    "machine": "605",
    "towersCount": "6",
    "gear": "(350)1/1",
    "sequence": "15",
    "farmName": "الجبلين",
    "movement": "دايري",
    "cropType": "برسيم",
    "hectareNumber": "28",
    "workerName": "بلال وبلال وراسل",
    "imageUrl": ""
  },
  {
    "name": "رشاش16",
    "machine": "411",
    "towersCount": "7",
    "gear": "(350)1/1",
    "sequence": "16",
    "farmName": "الجبلين",
    "movement": "نصف",
    "cropType": "برسيم",
    "hectareNumber": "20",
    "workerName": "بلال وبلال وراسل",
    "imageUrl": ""
  },
  {
    "name": "رشاش17",
    "machine": "605",
    "towersCount": "7",
    "gear": "(300)5/1",
    "sequence": "17",
    "farmName": "الجبلين",
    "movement": "نصف",
    "cropType": "رودس",
    "hectareNumber": "40",
    "workerName": "محمد خان",
    "imageUrl": ""
  },
  {
    "name": "رشاش18",
    "machine": "605",
    "towersCount": "8",
    "gear": "(425)1/1",
    "sequence": "18",
    "farmName": "الجبلين",
    "movement": ".دايري",
    "cropType": "زريعه",
    "hectareNumber": "52",
    "workerName": "راجو",
    "imageUrl": ""
  },
  {
    "name": "رشاش19",
    "machine": "411",
    "towersCount": "7",
    "gear": "(350)1/1",
    "sequence": "19",
    "farmName": "الجبلين",
    "movement": "نصف",
    "cropType": "رودس",
    "hectareNumber": "20",
    "workerName": "راجو",
    "imageUrl": ""
  },
  {
    "name": "رشاش20",
    "machine": "411",
    "towersCount": "6",
    "gear": "(350)1/1",
    "sequence": "20",
    "farmName": "الجبلين",
    "movement": "نصف",
    "cropType": "رودس",
    "hectareNumber": "15",
    "workerName": "بلال وبلال وراسل",
    "imageUrl": ""
  },
  {
    "name": "رشاش21",
    "machine": "411",
    "towersCount": "6",
    "gear": "(350)1/1",
    "sequence": "21",
    "farmName": "الجبلين",
    "movement": "دايري",
    "cropType": "رودس",
    "hectareNumber": "20",
    "workerName": "ابوالبشر",
    "imageUrl": ""
  },
  {
    "name": "رشاش22",
    "machine": "411",
    "towersCount": "6",
    "gear": "(350)1/1",
    "sequence": "22",
    "farmName": "الجبلين",
    "movement": "نصف",
    "cropType": "رودس",
    "hectareNumber": "15",
    "workerName": "ابوالبشر",
    "imageUrl": ""
  },
  {
    "name": "مكينة (المجلس)",
    "machine": "605",
    "towersCount": "",
    "gear": "1/1 (425)",
    "sequence": "",
    "farmName": "الجبلين",
    "movement": "",
    "cropType": "",
    "hectareNumber": "بلال وبلال وراسل",
    "workerName": "",
    "imageUrl": ""
  },
  {
    "name": "رشاش1",
    "machine": "411",
    "towersCount": "10",
    "gear": "1/1",
    "sequence": "1",
    "farmName": "الوسطي",
    "movement": "نصف دايري",
    "cropType": "",
    "hectareNumber": "25",
    "workerName": "جهنجير",
    "imageUrl": ""
  },
  {
    "name": "رشاش2",
    "machine": "411",
    "towersCount": "8",
    "gear": "1/1",
    "sequence": "2",
    "farmName": "الوسطي",
    "movement": "نصف دايري",
    "cropType": "",
    "hectareNumber": "25",
    "workerName": "جهنجير",
    "imageUrl": ""
  },
  {
    "name": "رشاش3",
    "machine": "411",
    "towersCount": "7",
    "gear": "1/1",
    "sequence": "3",
    "farmName": "الوسطي",
    "movement": "نصف دايري",
    "cropType": "",
    "hectareNumber": "20",
    "workerName": "جهنجير",
    "imageUrl": ""
  },
  {
    "name": "رشاش4",
    "machine": "411",
    "towersCount": "8",
    "gear": "1/1",
    "sequence": "4",
    "farmName": "الوسطي",
    "movement": "نصف دايري",
    "cropType": "",
    "hectareNumber": "25",
    "workerName": "جهنجير",
    "imageUrl": ""
  },
  {
    "name": "رشاش5",
    "machine": "411",
    "towersCount": "8",
    "gear": "1/1",
    "sequence": "5",
    "farmName": "الوسطي",
    "movement": "نصف دايري",
    "cropType": "",
    "hectareNumber": "25",
    "workerName": "جهنجير",
    "imageUrl": ""
  },
  {
    "name": "رشاش6",
    "machine": "411",
    "towersCount": "6",
    "gear": "1/1",
    "sequence": "6",
    "farmName": "الوسطي",
    "movement": "نصف دايري",
    "cropType": "",
    "hectareNumber": "15",
    "workerName": "جهنجير",
    "imageUrl": ""
  },
  {
    "name": "رشاش7",
    "machine": "411",
    "towersCount": "6",
    "gear": "1/1",
    "sequence": "7",
    "farmName": "الوسطي",
    "movement": "دايري",
    "cropType": "",
    "hectareNumber": "28",
    "workerName": "جهنجير",
    "imageUrl": ""
  }
];
