export const sprinklersSeed = [
  {
    "name": "رشاش1",
    "machine": "411",
    "towersCount": "5",
    "gear": "1/1(350)",
    "sequence": "1",
    "farmName": "الصناعيه",
    "movement": "دايري",
    "cropType": "رودس",
    "hectareNumber": "20",
    "workerName": "حسن رشاش",
    "workerPhone": "554767702",
    "imageUrl": "",
    "sourceSection": "رشاشات ومكاين الصناعيه",
    "sourceRow": 490
  },
  {
    "name": "رشاش2",
    "machine": "دينامو",
    "towersCount": "7",
    "gear": "",
    "sequence": "2",
    "farmName": "الصناعيه",
    "movement": "دايري",
    "cropType": "برسيم",
    "hectareNumber": "35",
    "workerName": "حسنين ممتاج",
    "workerPhone": "554176509",
    "imageUrl": "",
    "sourceSection": "رشاشات ومكاين الصناعيه",
    "sourceRow": 491
  },
  {
    "name": "رشاش3",
    "machine": "411",
    "towersCount": "8",
    "gear": "10/11(400)",
    "sequence": "3",
    "farmName": "الصناعيه",
    "movement": "نص",
    "cropType": "برسيم",
    "hectareNumber": "20",
    "workerName": "حسنين ممتاج",
    "workerPhone": "554176509",
    "imageUrl": "",
    "sourceSection": "رشاشات ومكاين الصناعيه",
    "sourceRow": 492
  },
  {
    "name": "رشاش5",
    "machine": "411",
    "towersCount": "7",
    "gear": "5/6(350)",
    "sequence": "5",
    "farmName": "الصناعيه",
    "movement": "نصين",
    "cropType": "برسيم",
    "hectareNumber": "38",
    "workerName": "كول محمد",
    "workerPhone": "542337261",
    "imageUrl": "",
    "sourceSection": "رشاشات ومكاين الصناعيه",
    "sourceRow": 493
  },
  {
    "name": "رشاش6",
    "machine": "411",
    "towersCount": "7",
    "gear": "1/1(350)",
    "sequence": "6",
    "farmName": "الصناعيه",
    "movement": "نصين",
    "cropType": "برسيم",
    "hectareNumber": "43",
    "workerName": "كول محمد",
    "workerPhone": "542337261",
    "imageUrl": "",
    "sourceSection": "رشاشات ومكاين الصناعيه",
    "sourceRow": 494
  },
  {
    "name": "رشاش7",
    "machine": "605",
    "towersCount": "6",
    "gear": "10/11(425)",
    "sequence": "7",
    "farmName": "الصناعيه",
    "movement": "داىري",
    "cropType": "برسيم",
    "hectareNumber": "38",
    "workerName": "بولوي",
    "workerPhone": "573449107",
    "imageUrl": "",
    "sourceSection": "رشاشات ومكاين الصناعيه",
    "sourceRow": 495
  },
  {
    "name": "رشاش8",
    "machine": "411",
    "towersCount": "5",
    "gear": "1/1(350)",
    "sequence": "8",
    "farmName": "الصناعيه",
    "movement": "دايري",
    "cropType": "برسيم",
    "hectareNumber": "25",
    "workerName": "نظر الإسلام",
    "workerPhone": "531389055",
    "imageUrl": "",
    "sourceSection": "رشاشات ومكاين الصناعيه",
    "sourceRow": 496
  },
  {
    "name": "رشاش1",
    "machine": "605",
    "towersCount": "9",
    "gear": "10/11",
    "sequence": "1",
    "farmName": "مجدل",
    "movement": "دايري",
    "cropType": "برسيم",
    "hectareNumber": "38",
    "workerName": "سلطان",
    "workerPhone": "530236572",
    "imageUrl": "",
    "sourceSection": "رشاشات ومكاين مجدل",
    "sourceRow": 501
  },
  {
    "name": "رشاش4",
    "machine": "411",
    "towersCount": "8",
    "gear": "1/1(350)",
    "sequence": "4",
    "farmName": "مجدل",
    "movement": "دايري",
    "cropType": "ذره",
    "hectareNumber": "31",
    "workerName": "سلمان عبد القدير",
    "workerPhone": "503620508",
    "imageUrl": "",
    "sourceSection": "رشاشات ومكاين مجدل",
    "sourceRow": 502
  },
  {
    "name": "رشاش6",
    "machine": "411",
    "towersCount": "8",
    "gear": "1/1(350)",
    "sequence": "6",
    "farmName": "مجدل",
    "movement": "دايري",
    "cropType": "رودس",
    "hectareNumber": "34",
    "workerName": "عبدالله صالح",
    "workerPhone": "508989401",
    "imageUrl": "",
    "sourceSection": "رشاشات ومكاين مجدل",
    "sourceRow": 503
  },
  {
    "name": "رشاش7",
    "machine": "411",
    "towersCount": "6",
    "gear": "1/1(350)",
    "sequence": "7",
    "farmName": "مجدل",
    "movement": "دايري",
    "cropType": "ذره",
    "hectareNumber": "26",
    "workerName": "عدي",
    "workerPhone": "544589308",
    "imageUrl": "",
    "sourceSection": "رشاشات ومكاين مجدل",
    "sourceRow": 504
  },
  {
    "name": "رشاش8",
    "machine": "605",
    "towersCount": "7",
    "gear": "10/11",
    "sequence": "8",
    "farmName": "مجدل",
    "movement": "دايري",
    "cropType": "رودس",
    "hectareNumber": "44",
    "workerName": "عبدالسلام",
    "workerPhone": "565428028",
    "imageUrl": "",
    "sourceSection": "رشاشات ومكاين مجدل",
    "sourceRow": 505
  },
  {
    "name": "رشاش9",
    "machine": "411",
    "towersCount": "6",
    "gear": "1/1(350)",
    "sequence": "9",
    "farmName": "مجدل",
    "movement": "دايري",
    "cropType": "برسيم",
    "hectareNumber": "26",
    "workerName": "عبدالسلام",
    "workerPhone": "565428028",
    "imageUrl": "",
    "sourceSection": "رشاشات ومكاين مجدل",
    "sourceRow": 506
  },
  {
    "name": "رشاش10",
    "machine": "411",
    "towersCount": "6",
    "gear": "1/1",
    "sequence": "10",
    "farmName": "مجدل",
    "movement": "دايري",
    "cropType": "برسيم",
    "hectareNumber": "29",
    "workerName": "امين",
    "workerPhone": "558536003",
    "imageUrl": "",
    "sourceSection": "رشاشات ومكاين مجدل",
    "sourceRow": 507
  },
  {
    "name": "رشاش11",
    "machine": "411",
    "towersCount": "7",
    "gear": "1/1",
    "sequence": "11",
    "farmName": "مجدل",
    "movement": "ثلاث اربع",
    "cropType": "برسيم",
    "hectareNumber": "34",
    "workerName": "امين",
    "workerPhone": "558536003",
    "imageUrl": "",
    "sourceSection": "رشاشات ومكاين مجدل",
    "sourceRow": 508
  },
  {
    "name": "رشاش12",
    "machine": "411",
    "towersCount": "8",
    "gear": "1/1",
    "sequence": "12",
    "farmName": "مجدل",
    "movement": "نص",
    "cropType": "رودس",
    "hectareNumber": "25",
    "workerName": "محمد اسلام",
    "workerPhone": "564610350",
    "imageUrl": "",
    "sourceSection": "رشاشات ومكاين مجدل",
    "sourceRow": 509
  },
  {
    "name": "رشاش13",
    "machine": "605",
    "towersCount": "7",
    "gear": "10/11",
    "sequence": "13",
    "farmName": "مجدل",
    "movement": "ثلاث اربع",
    "cropType": "برسيم",
    "hectareNumber": "32",
    "workerName": "عماد عبد الصالح عبدالله",
    "workerPhone": "561762311",
    "imageUrl": "",
    "sourceSection": "رشاشات ومكاين مجدل",
    "sourceRow": 510
  },
  {
    "name": "رشاش1",
    "machine": "411",
    "towersCount": "7",
    "gear": "1/1(425)",
    "sequence": "1",
    "farmName": "الخطمي",
    "movement": "دايري",
    "cropType": "برسيم",
    "hectareNumber": "40",
    "workerName": "نواب",
    "workerPhone": "567695772",
    "imageUrl": "",
    "sourceSection": "رشاشات ومكاين الخطمي",
    "sourceRow": 515
  },
  {
    "name": "رشاش2",
    "machine": "411",
    "towersCount": "10",
    "gear": "1/1(350)",
    "sequence": "2",
    "farmName": "الخطمي",
    "movement": "دايري",
    "cropType": "رودس",
    "hectareNumber": "50",
    "workerName": "رياض",
    "workerPhone": "557695772",
    "imageUrl": "",
    "sourceSection": "رشاشات ومكاين الخطمي",
    "sourceRow": 516
  },
  {
    "name": "رشاش3",
    "machine": "411",
    "towersCount": "7",
    "gear": "1/1(350)",
    "sequence": "3",
    "farmName": "الخطمي",
    "movement": "نصف دايري",
    "cropType": "برسيم",
    "hectareNumber": "20",
    "workerName": "فتحي محمد",
    "workerPhone": "545968627",
    "imageUrl": "",
    "sourceSection": "رشاشات ومكاين الخطمي",
    "sourceRow": 517
  },
  {
    "name": "رشاش4",
    "machine": "411",
    "towersCount": "10",
    "gear": "1/1(350)",
    "sequence": "4",
    "farmName": "الخطمي",
    "movement": "نصف دايري",
    "cropType": "برسيم",
    "hectareNumber": "35",
    "workerName": "شمس الإسلام",
    "workerPhone": "548995123",
    "imageUrl": "",
    "sourceSection": "رشاشات ومكاين الخطمي",
    "sourceRow": 518
  },
  {
    "name": "رشاش5",
    "machine": "411",
    "towersCount": "7",
    "gear": "1/1(350)",
    "sequence": "5",
    "farmName": "الخطمي",
    "movement": "دايري",
    "cropType": "برسيم",
    "hectareNumber": "40",
    "workerName": "فتحي محمد",
    "workerPhone": "545968627",
    "imageUrl": "",
    "sourceSection": "رشاشات ومكاين الخطمي",
    "sourceRow": 519
  },
  {
    "name": "رشاش6",
    "machine": "411",
    "towersCount": "8",
    "gear": "1/1(350)",
    "sequence": "6",
    "farmName": "الخطمي",
    "movement": "نصف دايري",
    "cropType": "رودس",
    "hectareNumber": "25",
    "workerName": "امتياج احمد",
    "workerPhone": "541673502",
    "imageUrl": "",
    "sourceSection": "رشاشات ومكاين الخطمي",
    "sourceRow": 520
  },
  {
    "name": "رشاش7",
    "machine": "411",
    "towersCount": "10",
    "gear": "1/1(350)",
    "sequence": "7",
    "farmName": "الخطمي",
    "movement": "دايري",
    "cropType": "رودس",
    "hectareNumber": "50",
    "workerName": "مد ولايت",
    "workerPhone": "542424491",
    "imageUrl": "",
    "sourceSection": "رشاشات ومكاين الخطمي",
    "sourceRow": 521
  },
  {
    "name": "رشاش8",
    "machine": "411",
    "towersCount": "8",
    "gear": "1/1(350)",
    "sequence": "8",
    "farmName": "الخطمي",
    "movement": "دايري",
    "cropType": "رودس",
    "hectareNumber": "42",
    "workerName": "مد ولايت",
    "workerPhone": "542424491",
    "imageUrl": "",
    "sourceSection": "رشاشات ومكاين الخطمي",
    "sourceRow": 522
  },
  {
    "name": "رشاش9",
    "machine": "411",
    "towersCount": "8",
    "gear": "1/1(350)",
    "sequence": "9",
    "farmName": "الخطمي",
    "movement": "دايري",
    "cropType": "رودس",
    "hectareNumber": "30",
    "workerName": "امتياج احمد",
    "workerPhone": "541673502",
    "imageUrl": "",
    "sourceSection": "رشاشات ومكاين الخطمي",
    "sourceRow": 523
  },
  {
    "name": "رشاش10",
    "machine": "411",
    "towersCount": "8",
    "gear": "1/1(350)",
    "sequence": "10",
    "farmName": "الخطمي",
    "movement": "دايري",
    "cropType": "رودس",
    "hectareNumber": "41",
    "workerName": "صلاح الدين",
    "workerPhone": "563453593",
    "imageUrl": "",
    "sourceSection": "رشاشات ومكاين الخطمي",
    "sourceRow": 524
  },
  {
    "name": "رشاش 11",
    "machine": "411",
    "towersCount": "8",
    "gear": "1/1(350)",
    "sequence": "11",
    "farmName": "الخطمي",
    "movement": "نصف دايري",
    "cropType": "برسيم",
    "hectareNumber": "25",
    "workerName": "صلاح الدين",
    "workerPhone": "563453593",
    "imageUrl": "",
    "sourceSection": "رشاشات ومكاين الخطمي",
    "sourceRow": 525
  },
  {
    "name": "رشاش 1",
    "machine": "411",
    "towersCount": "8",
    "gear": "1/1",
    "sequence": "1",
    "farmName": "الحوطي",
    "movement": "نصف دايري",
    "cropType": "ذره",
    "hectareNumber": "25",
    "workerName": "ارشد وكمال",
    "workerPhone": "591039397",
    "imageUrl": "",
    "sourceSection": "رشاشات ومكاين الحوطي",
    "sourceRow": 532
  },
  {
    "name": "رشاش2",
    "machine": "411",
    "towersCount": "8",
    "gear": "1/1",
    "sequence": "2",
    "farmName": "الحوطي",
    "movement": "نصف دايري",
    "cropType": "ذره",
    "hectareNumber": "25",
    "workerName": "ارشد وكمال",
    "workerPhone": "591039397",
    "imageUrl": "",
    "sourceSection": "رشاشات ومكاين الحوطي",
    "sourceRow": 533
  },
  {
    "name": "رشاش3",
    "machine": "411",
    "towersCount": "9",
    "gear": "1/1",
    "sequence": "3",
    "farmName": "الحوطي",
    "movement": "نصف دايري",
    "cropType": "ذره",
    "hectareNumber": "32",
    "workerName": "كمال",
    "workerPhone": "55096951",
    "imageUrl": "",
    "sourceSection": "رشاشات ومكاين الحوطي",
    "sourceRow": 534
  },
  {
    "name": "رشاش4",
    "machine": "411",
    "towersCount": "8",
    "gear": "",
    "sequence": "4",
    "farmName": "الحوطي",
    "movement": "نصف دايري",
    "cropType": "ذره",
    "hectareNumber": "30",
    "workerName": "ارشد وكمال",
    "workerPhone": "591039397",
    "imageUrl": "",
    "sourceSection": "رشاشات ومكاين الحوطي",
    "sourceRow": 535
  },
  {
    "name": "رشاش5",
    "machine": "411",
    "towersCount": "9",
    "gear": "1/1",
    "sequence": "5",
    "farmName": "الحوطي",
    "movement": "نصف دايري",
    "cropType": "ذره",
    "hectareNumber": "32",
    "workerName": "ارشد وكمال",
    "workerPhone": "591039397",
    "imageUrl": "",
    "sourceSection": "رشاشات ومكاين الحوطي",
    "sourceRow": 536
  },
  {
    "name": "رشاش6",
    "machine": "411",
    "towersCount": "8",
    "gear": "1/1",
    "sequence": "6",
    "farmName": "الحوطي",
    "movement": "نصف دايري",
    "cropType": "ذره",
    "hectareNumber": "25",
    "workerName": "ارشد وكمال",
    "workerPhone": "591039397",
    "imageUrl": "",
    "sourceSection": "رشاشات ومكاين الحوطي",
    "sourceRow": 537
  },
  {
    "name": "رشاش9",
    "machine": "411",
    "towersCount": "7",
    "gear": "1/1",
    "sequence": "9",
    "farmName": "الحوطي",
    "movement": "نصف دايري",
    "cropType": "رودس",
    "hectareNumber": "20",
    "workerName": "ارشد وكمال",
    "workerPhone": "591039397",
    "imageUrl": "",
    "sourceSection": "رشاشات ومكاين الحوطي",
    "sourceRow": 538
  },
  {
    "name": "رشاش10",
    "machine": "411",
    "towersCount": "5",
    "gear": "1/1",
    "sequence": "10",
    "farmName": "الحوطي",
    "movement": "دايري",
    "cropType": "رودس",
    "hectareNumber": "20",
    "workerName": "كمال",
    "workerPhone": "55096951",
    "imageUrl": "",
    "sourceSection": "رشاشات ومكاين الحوطي",
    "sourceRow": 539
  },
  {
    "name": "رشاش11",
    "machine": "",
    "towersCount": "4",
    "gear": "",
    "sequence": "11",
    "farmName": "الحوطي",
    "movement": "",
    "cropType": "",
    "hectareNumber": "",
    "workerName": "ارشد وكمال",
    "workerPhone": "591039397",
    "imageUrl": "",
    "sourceSection": "رشاشات ومكاين الحوطي",
    "sourceRow": 540
  },
  {
    "name": "رشاش الحوطي الجديد",
    "machine": "",
    "towersCount": "7",
    "gear": "",
    "sequence": "",
    "farmName": "الحوطي",
    "movement": "دايري",
    "cropType": "",
    "hectareNumber": "",
    "workerName": "ارشد وكمال",
    "workerPhone": "591039397",
    "imageUrl": "",
    "sourceSection": "رشاشات ومكاين الحوطي",
    "sourceRow": 541
  },
  {
    "name": "رشاش الحوطي الجديد",
    "machine": "411",
    "towersCount": "8",
    "gear": "(350)1/1",
    "sequence": "",
    "farmName": "الحوطي",
    "movement": "",
    "cropType": "",
    "hectareNumber": "",
    "workerName": "ارشد وكمال",
    "workerPhone": "591039397",
    "imageUrl": "",
    "sourceSection": "رشاشات ومكاين الحوطي",
    "sourceRow": 542
  },
  {
    "name": "رشاش7",
    "machine": "411",
    "towersCount": "9",
    "gear": "1/1",
    "sequence": "7",
    "farmName": "الجبلين",
    "movement": "نصف دايري",
    "cropType": "ذره",
    "hectareNumber": "32",
    "workerName": "راجو",
    "workerPhone": "560644183",
    "imageUrl": "",
    "sourceSection": "رشاشات ومكاين الجبلين",
    "sourceRow": 547
  },
  {
    "name": "رشاش8",
    "machine": "411",
    "towersCount": "8",
    "gear": "1/1",
    "sequence": "8",
    "farmName": "الجبلين",
    "movement": "نصف دايري",
    "cropType": "ذره",
    "hectareNumber": "25",
    "workerName": "راجو",
    "workerPhone": "560644183",
    "imageUrl": "",
    "sourceSection": "رشاشات ومكاين الجبلين",
    "sourceRow": 548
  },
  {
    "name": "رشاش12",
    "machine": "605",
    "towersCount": "9",
    "gear": ".(425)1/1",
    "sequence": "12",
    "farmName": "الجبلين",
    "movement": "ثلاث اربع دايره",
    "cropType": "برسيم",
    "hectareNumber": "35",
    "workerName": "بلال وبلال وراسل",
    "workerPhone": "596138534",
    "imageUrl": "",
    "sourceSection": "رشاشات ومكاين الجبلين",
    "sourceRow": 549
  },
  {
    "name": "رشاش13",
    "machine": "605",
    "towersCount": "8",
    "gear": ".(425)1/1",
    "sequence": "13",
    "farmName": "الجبلين",
    "movement": "دايري",
    "cropType": "زريعه",
    "hectareNumber": "52",
    "workerName": "بلال وبلال وراسل",
    "workerPhone": "596138534",
    "imageUrl": "",
    "sourceSection": "رشاشات ومكاين الجبلين",
    "sourceRow": 550
  },
  {
    "name": "رشاش14",
    "machine": "605",
    "towersCount": "8",
    "gear": ".(425)1/1",
    "sequence": "14",
    "farmName": "الجبلين",
    "movement": "دايري",
    "cropType": "زريعه",
    "hectareNumber": "51",
    "workerName": "بلال وبلال وراسل",
    "workerPhone": "596138534",
    "imageUrl": "",
    "sourceSection": "رشاشات ومكاين الجبلين",
    "sourceRow": 551
  },
  {
    "name": "رشاش15",
    "machine": "605",
    "towersCount": "6",
    "gear": "(350)1/1",
    "sequence": "15",
    "farmName": "الجبلين",
    "movement": "دايري",
    "cropType": "برسيم",
    "hectareNumber": "28",
    "workerName": "بلال وبلال وراسل",
    "workerPhone": "596138534",
    "imageUrl": "",
    "sourceSection": "رشاشات ومكاين الجبلين",
    "sourceRow": 552
  },
  {
    "name": "رشاش16",
    "machine": "411",
    "towersCount": "7",
    "gear": "(350)1/1",
    "sequence": "16",
    "farmName": "الجبلين",
    "movement": "نصف",
    "cropType": "برسيم",
    "hectareNumber": "20",
    "workerName": "بلال وبلال وراسل",
    "workerPhone": "596138534",
    "imageUrl": "",
    "sourceSection": "رشاشات ومكاين الجبلين",
    "sourceRow": 553
  },
  {
    "name": "رشاش17",
    "machine": "605",
    "towersCount": "7",
    "gear": "(300)5/1",
    "sequence": "17",
    "farmName": "الجبلين",
    "movement": "نصف",
    "cropType": "رودس",
    "hectareNumber": "40",
    "workerName": "محمد خان",
    "workerPhone": "553827559",
    "imageUrl": "",
    "sourceSection": "رشاشات ومكاين الجبلين",
    "sourceRow": 554
  },
  {
    "name": "رشاش18",
    "machine": "605",
    "towersCount": "8",
    "gear": "(425)1/1",
    "sequence": "18",
    "farmName": "الجبلين",
    "movement": ".دايري",
    "cropType": "زريعه",
    "hectareNumber": "52",
    "workerName": "راجو",
    "workerPhone": "560644183",
    "imageUrl": "",
    "sourceSection": "رشاشات ومكاين الجبلين",
    "sourceRow": 555
  },
  {
    "name": "رشاش19",
    "machine": "411",
    "towersCount": "7",
    "gear": "(350)1/1",
    "sequence": "19",
    "farmName": "الجبلين",
    "movement": "نصف",
    "cropType": "رودس",
    "hectareNumber": "20",
    "workerName": "راجو",
    "workerPhone": "560644183",
    "imageUrl": "",
    "sourceSection": "رشاشات ومكاين الجبلين",
    "sourceRow": 556
  },
  {
    "name": "رشاش20",
    "machine": "411",
    "towersCount": "6",
    "gear": "(350)1/1",
    "sequence": "20",
    "farmName": "الجبلين",
    "movement": "نصف",
    "cropType": "رودس",
    "hectareNumber": "15",
    "workerName": "بلال وبلال وراسل",
    "workerPhone": "596138534",
    "imageUrl": "",
    "sourceSection": "رشاشات ومكاين الجبلين",
    "sourceRow": 557
  },
  {
    "name": "رشاش21",
    "machine": "411",
    "towersCount": "6",
    "gear": "(350)1/1",
    "sequence": "21",
    "farmName": "الجبلين",
    "movement": "دايري",
    "cropType": "رودس",
    "hectareNumber": "20",
    "workerName": "ابوالبشر",
    "workerPhone": "س",
    "imageUrl": "",
    "sourceSection": "رشاشات ومكاين الجبلين",
    "sourceRow": 558
  },
  {
    "name": "رشاش22",
    "machine": "411",
    "towersCount": "6",
    "gear": "(350)1/1",
    "sequence": "22",
    "farmName": "الجبلين",
    "movement": "نصف",
    "cropType": "رودس",
    "hectareNumber": "15",
    "workerName": "ابوالبشر",
    "workerPhone": "",
    "imageUrl": "",
    "sourceSection": "رشاشات ومكاين الجبلين",
    "sourceRow": 559
  },
  {
    "name": "مكينة (المجلس)",
    "machine": "605",
    "towersCount": "",
    "gear": "1/1 (425)",
    "sequence": "",
    "farmName": "الجبلين",
    "movement": "",
    "cropType": "",
    "hectareNumber": "بلال وبلال وراسل",
    "workerName": "",
    "workerPhone": "596138534",
    "imageUrl": "",
    "sourceSection": "رشاشات ومكاين الجبلين",
    "sourceRow": 560
  },
  {
    "name": "رشاش1",
    "machine": "411",
    "towersCount": "10",
    "gear": "1/1",
    "sequence": "1",
    "farmName": "الوسطي",
    "movement": "نصف دايري",
    "cropType": "",
    "hectareNumber": "25",
    "workerName": "جهنجير",
    "workerPhone": "508169161",
    "imageUrl": "",
    "sourceSection": "رشاشات ومكاين الوسطي",
    "sourceRow": 566
  },
  {
    "name": "رشاش2",
    "machine": "411",
    "towersCount": "8",
    "gear": "1/1",
    "sequence": "2",
    "farmName": "الوسطي",
    "movement": "نصف دايري",
    "cropType": "",
    "hectareNumber": "25",
    "workerName": "جهنجير",
    "workerPhone": "508169161",
    "imageUrl": "",
    "sourceSection": "رشاشات ومكاين الوسطي",
    "sourceRow": 567
  },
  {
    "name": "رشاش3",
    "machine": "411",
    "towersCount": "7",
    "gear": "1/1",
    "sequence": "3",
    "farmName": "الوسطي",
    "movement": "نصف دايري",
    "cropType": "",
    "hectareNumber": "20",
    "workerName": "جهنجير",
    "workerPhone": "508169161",
    "imageUrl": "",
    "sourceSection": "رشاشات ومكاين الوسطي",
    "sourceRow": 568
  },
  {
    "name": "رشاش4",
    "machine": "411",
    "towersCount": "8",
    "gear": "1/1",
    "sequence": "4",
    "farmName": "الوسطي",
    "movement": "نصف دايري",
    "cropType": "",
    "hectareNumber": "25",
    "workerName": "جهنجير",
    "workerPhone": "508169161",
    "imageUrl": "",
    "sourceSection": "رشاشات ومكاين الوسطي",
    "sourceRow": 569
  },
  {
    "name": "رشاش5",
    "machine": "411",
    "towersCount": "8",
    "gear": "1/1",
    "sequence": "5",
    "farmName": "الوسطي",
    "movement": "نصف دايري",
    "cropType": "",
    "hectareNumber": "25",
    "workerName": "جهنجير",
    "workerPhone": "508169161",
    "imageUrl": "",
    "sourceSection": "رشاشات ومكاين الوسطي",
    "sourceRow": 570
  },
  {
    "name": "رشاش6",
    "machine": "411",
    "towersCount": "6",
    "gear": "1/1",
    "sequence": "6",
    "farmName": "الوسطي",
    "movement": "نصف دايري",
    "cropType": "",
    "hectareNumber": "15",
    "workerName": "جهنجير",
    "workerPhone": "508169161",
    "imageUrl": "",
    "sourceSection": "رشاشات ومكاين الوسطي",
    "sourceRow": 571
  },
  {
    "name": "رشاش7",
    "machine": "411",
    "towersCount": "6",
    "gear": "1/1",
    "sequence": "7",
    "farmName": "الوسطي",
    "movement": "دايري",
    "cropType": "",
    "hectareNumber": "28",
    "workerName": "جهنجير",
    "workerPhone": "508169161",
    "imageUrl": "",
    "sourceSection": "رشاشات ومكاين الوسطي",
    "sourceRow": 572
  }
];
