import { useEffect, useState } from "react";
import { useRouter } from "next/router";
import { collection, doc, getDoc, getDocs, serverTimestamp, updateDoc } from "firebase/firestore";
import { db } from "../../../lib/firebase";
import ProtectedRoute from "../../../components/ProtectedRoute";
import Layout from "../../../components/Layout";

const statuses = ["صالح", "عاطل", "تالف"];
const types = ["معدة", "سيارة", "ماكينة", "أداة", "أخرى"];

export default function EditAsset(){
 const router=useRouter(); const {id}=router.query; const [workers,setWorkers]=useState([]); const [farms,setFarms]=useState([]); const [image,setImage]=useState(null); const [loading,setLoading]=useState(false);
 const [form,setForm]=useState({name:"",code:"",type:"معدة",status:"صالح",farmId:"",workerIds:[],notes:"",imageUrl:""});
 useEffect(()=>{getDocs(collection(db,"workers")).then(s=>setWorkers(s.docs.map(d=>({id:d.id,...d.data()})))); getDocs(collection(db,"farms")).then(s=>setFarms(s.docs.map(d=>({id:d.id,...d.data()}))));},[]);
 useEffect(()=>{if(!id)return; getDoc(doc(db,"assets",id)).then(s=>{if(s.exists()) setForm(p=>({...p,...s.data(),workerIds:s.data().workerIds||[]}));});},[id]);
 const toggleWorker=(wid)=>setForm(p=>({ ...p, workerIds:p.workerIds.includes(wid)?p.workerIds.filter(x=>x!==wid):[...p.workerIds,wid] }));
 const upload=async()=>{if(!image)return form.imageUrl||""; const cloudName=process.env.NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME; const preset=process.env.NEXT_PUBLIC_CLOUDINARY_UPLOAD_PRESET; const data=new FormData(); data.append("file",image); data.append("upload_preset",preset); const res=await fetch(`https://api.cloudinary.com/v1_1/${cloudName}/image/upload`,{method:"POST",body:data}); const json=await res.json(); if(!json.secure_url) throw new Error("Upload failed"); return json.secure_url;};
 const submit=async(e)=>{e.preventDefault(); if(!form.name||!form.farmId) return alert("اسم المعدة والمزرعة مطلوبان"); setLoading(true); try{const farm=farms.find(f=>f.id===form.farmId); const selectedWorkers=workers.filter(w=>form.workerIds.includes(w.id)); const imageUrl=await upload(); await updateDoc(doc(db,"assets",id),{name:form.name,code:form.code||"",type:form.type,status:form.status,farmId:form.farmId,farmName:farm?.name||"",workerIds:form.workerIds,workers:selectedWorkers.map(w=>({id:w.id,name:w.name,phone:w.phone||""})),workerNames:selectedWorkers.map(w=>w.name).join("، "),imageUrl,notes:form.notes||"",updatedAt:serverTimestamp()}); router.push("/assets");}catch(e){console.error(e); alert("حدث خطأ أثناء الحفظ"); setLoading(false);}};
 return <ProtectedRoute><Layout title="تعديل معدة"><form onSubmit={submit} className="page-card max-w-4xl p-5 space-y-4"><div className="grid gap-4 md:grid-cols-2"><input className="form-input" placeholder="اسم المعدة" value={form.name||""} onChange={e=>setForm({...form,name:e.target.value})}/><input className="form-input" placeholder="كود أو رقم المعدة اختياري" value={form.code||""} onChange={e=>setForm({...form,code:e.target.value})}/></div><div className="grid gap-4 md:grid-cols-3"><select className="form-input" value={form.farmId||""} onChange={e=>setForm({...form,farmId:e.target.value})}><option value="">اختر المزرعة</option>{farms.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select><select className="form-input" value={form.type||"معدة"} onChange={e=>setForm({...form,type:e.target.value})}>{types.map(x=><option key={x}>{x}</option>)}</select><select className="form-input" value={form.status||"صالح"} onChange={e=>setForm({...form,status:e.target.value})}>{statuses.map(x=><option key={x}>{x}</option>)}</select></div><div><label className="mb-2 block text-sm font-black text-slate-700">العمال المستلمون للمعدة</label><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{workers.map(w=><label key={w.id} className={`flex cursor-pointer items-center gap-3 rounded-2xl border p-3 text-sm font-bold ${form.workerIds?.includes(w.id)?"border-green-600 bg-green-50 text-green-800":"border-slate-200 bg-white text-slate-700"}`}><input type="checkbox" checked={form.workerIds?.includes(w.id)} onChange={()=>toggleWorker(w.id)}/>{w.name}</label>)}</div></div>{form.imageUrl&&<img src={form.imageUrl} className="h-40 w-full rounded-2xl object-cover" alt={form.name}/>}<input type="file" accept="image/*" capture="environment" className="form-input" onChange={e=>setImage(e.target.files?.[0]||null)}/><textarea className="form-input h-28" placeholder="ملاحظات" value={form.notes||""} onChange={e=>setForm({...form,notes:e.target.value})}/><button disabled={loading} className="btn-primary">{loading?"جاري الحفظ...":"حفظ التعديلات"}</button></form></Layout></ProtectedRoute>;
}
