import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { collection, getDocs } from "firebase/firestore";
import { db } from "../lib/firebase";
import ProtectedRoute from "../components/ProtectedRoute";
import Layout from "../components/Layout";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faTractor, faUsers, faWheatAwn, faCircleCheck, faTriangleExclamation, faCircleXmark, faUserTie, faWarehouse, faLayerGroup, faLocationDot } from "@fortawesome/free-solid-svg-icons";
const countBy=(arr,key,fallback="غير محدد")=>arr.reduce((acc,x)=>{const v=x[key]||fallback; acc[v]=(acc[v]||0)+1; return acc;},{});
function StatCard({title,value,href,icon,sub}){return <Link href={href} className="page-card group p-5 transition hover:-translate-y-1 hover:shadow-lg"><div className="flex items-start justify-between gap-4"><div><p className="text-sm font-bold text-slate-500">{title}</p><h3 className="mt-2 text-4xl font-black text-slate-900">{value}</h3><p className="mt-2 text-xs text-slate-400">{sub}</p></div><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-green-50 text-green-700 group-hover:bg-green-700 group-hover:text-white"><FontAwesomeIcon icon={icon}/></div></div></Link>}
function MiniTable({title,items,empty="لا توجد بيانات"}){return <div className="page-card p-5"><h3 className="mb-4 font-black">{title}</h3><div className="space-y-2">{items.length?items.map((x,i)=><Link key={i} href={x.href} className="flex items-center justify-between rounded-2xl border border-slate-100 p-3 hover:bg-slate-50"><span className="font-bold text-slate-700">{x.label}</span><span className="badge bg-slate-100 text-slate-700">{x.count}</span></Link>):<p className="text-sm text-slate-400">{empty}</p>}</div></div>}
export default function Dashboard(){
 const [assets,setAssets]=useState([]); const [workers,setWorkers]=useState([]); const [farms,setFarms]=useState([]); const [engineers,setEngineers]=useState([]); const [kubras,setKubras]=useState([]); const [types,setTypes]=useState([]);
 useEffect(()=>{Promise.all([getDocs(collection(db,"assets")),getDocs(collection(db,"workers")),getDocs(collection(db,"farms")),getDocs(collection(db,"engineers")),getDocs(collection(db,"kubras")),getDocs(collection(db,"assetTypes"))]).then(([a,w,f,e,k,t])=>{setAssets(a.docs.map(d=>({id:d.id,...d.data()}))); setWorkers(w.docs.map(d=>({id:d.id,...d.data()}))); setFarms(f.docs.map(d=>({id:d.id,...d.data()}))); setEngineers(e.docs.map(d=>({id:d.id,...d.data()}))); setKubras(k.docs.map(d=>({id:d.id,...d.data()}))); setTypes(t.docs.map(d=>({id:d.id,...d.data()})));});},[]);
 const stats=useMemo(()=>({total:assets.length,good:assets.filter(a=>a.status==="صالح").length,broken:assets.filter(a=>a.status==="عاطل").length,damaged:assets.filter(a=>a.status==="تالف").length,inFarms:assets.filter(a=>a.placeType==="farm").length,inKubras:assets.filter(a=>a.placeType==="kubra").length}),[assets]);
 const cards=[{title:"إجمالي المعدات",value:stats.total,href:"/assets",icon:faTractor,sub:"كل المعدات والعهد"},{title:"المعدات الصالحة",value:stats.good,href:"/assets?status=صالح",icon:faCircleCheck,sub:"اضغط لعرض الصالح"},{title:"المعدات العاطلة",value:stats.broken,href:"/assets?status=عاطل",icon:faTriangleExclamation,sub:"تحتاج متابعة"},{title:"المعدات التالفة",value:stats.damaged,href:"/assets?status=تالف",icon:faCircleXmark,sub:"خارج الخدمة"},{title:"داخل المزارع",value:stats.inFarms,href:"/assets?placeType=farm",icon:faWheatAwn,sub:"معدات موجودة في المزارع"},{title:"داخل الكِبر",value:stats.inKubras,href:"/assets?placeType=kubra",icon:faWarehouse,sub:"معدات موجودة في الكِبر"},{title:"أنواع المعدات",value:types.length,href:"/asset-types",icon:faLayerGroup,sub:"إضافة وتعديل الأنواع"},{title:"العمال",value:workers.length,href:"/workers",icon:faUsers,sub:"كل العمال"},{title:"المزارع",value:farms.length,href:"/farms",icon:faLocationDot,sub:"كل المزارع"},{title:"المهندسون",value:engineers.length,href:"/engineers",icon:faUserTie,sub:"مسئولو المزارع"}];
 const byType=types.map(t=>({label:t.name,count:assets.filter(a=>a.assetTypeId===t.id||(!a.assetTypeId&&t.name==="مكينة")).length,href:`/assets?assetTypeId=${t.id}`})).sort((a,b)=>b.count-a.count).slice(0,8);
 const byFarm=farms.map(f=>({label:f.name,count:assets.filter(a=>a.farmId===f.id||a.placeId===f.id).length,href:`/assets?farmId=${f.id}`})).sort((a,b)=>b.count-a.count).slice(0,8);
 const byKubra=kubras.map(k=>({label:k.name,count:assets.filter(a=>a.kubraId===k.id||a.placeId===k.id).length,href:`/assets?kubraId=${k.id}`})).sort((a,b)=>b.count-a.count).slice(0,8);
 const byWorker=workers.map(w=>({label:w.name,count:assets.filter(a=>(a.workerIds||[]).includes(w.id)).length,href:`/assets?workerId=${w.id}`})).sort((a,b)=>b.count-a.count).slice(0,8);
 return <ProtectedRoute><Layout title="لوحة التحكم"><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5">{cards.map(c=><StatCard key={c.title} {...c}/>)}</div><div className="mt-6 grid gap-4 xl:grid-cols-2"><MiniTable title="إحصائيات حسب نوع المعدة" items={byType}/><MiniTable title="إحصائيات حسب المزرعة" items={byFarm}/><MiniTable title="إحصائيات حسب الكِبرة" items={byKubra}/><MiniTable title="إحصائيات حسب العامل" items={byWorker}/></div><div className="mt-6 page-card overflow-x-auto"><h3 className="p-5 pb-2 font-black">آخر المعدات المسجلة</h3><table className="w-full"><thead className="bg-slate-50"><tr><th className="table-th">المعدة</th><th className="table-th">النوع</th><th className="table-th">المكان</th><th className="table-th">الحالة</th></tr></thead><tbody>{assets.slice(0,8).map(a=><tr key={a.id} className="clickable-row border-t border-slate-100"><td className="table-td font-bold"><Link href={`/assets/${a.id}`}>{a.name}</Link></td><td className="table-td">{a.assetTypeName||"مكينة"}</td><td className="table-td">{a.placeName||a.farmName||a.kubraName||"-"}</td><td className="table-td"><Link href={`/assets?status=${a.status}`} className="badge bg-slate-100 text-slate-700">{a.status}</Link></td></tr>)}</tbody></table></div></Layout></ProtectedRoute>;
}
